SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[silver_nyc_crashes]
(
	[CRASH_DATE] [varchar](8000)  NULL,
	[CRASH_TIME] [varchar](8000)  NULL,
	[BOROUGH] [varchar](8000)  NULL,
	[ZIP_CODE] [varchar](8000)  NULL,
	[LATITUDE] [varchar](8000)  NULL,
	[LONGITUDE] [varchar](8000)  NULL,
	[LOCATION] [varchar](8000)  NULL,
	[ON_STREET_NAME] [varchar](8000)  NULL,
	[CROSS_STREET_NAME] [varchar](8000)  NULL,
	[OFF_STREET_NAME] [varchar](8000)  NULL,
	[NUMBER_OF_PERSONS_INJURED] [varchar](8000)  NULL,
	[NUMBER_OF_PERSONS_KILLED] [varchar](8000)  NULL,
	[NUMBER_OF_PEDESTRIANS_INJURED] [varchar](8000)  NULL,
	[NUMBER_OF_PEDESTRIANS_KILLED] [varchar](8000)  NULL,
	[NUMBER_OF_CYCLIST_INJURED] [varchar](8000)  NULL,
	[NUMBER_OF_CYCLIST_KILLED] [varchar](8000)  NULL,
	[NUMBER_OF_MOTORIST_INJURED] [varchar](8000)  NULL,
	[NUMBER_OF_MOTORIST_KILLED] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_VEHICLE_1] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_VEHICLE_2] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_VEHICLE_3] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_VEHICLE_4] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_VEHICLE_5] [varchar](8000)  NULL,
	[COLLISION_ID] [varchar](8000)  NULL,
	[VEHICLE_TYPE_CODE_1] [varchar](8000)  NULL,
	[VEHICLE_TYPE_CODE_2] [varchar](8000)  NULL,
	[VEHICLE_TYPE_CODE_3] [varchar](8000)  NULL,
	[VEHICLE_TYPE_CODE_4] [varchar](8000)  NULL,
	[VEHICLE_TYPE_CODE_5] [varchar](8000)  NULL
)
GO ;

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[silver_nyc_vehicles]
(
	[UNIQUE_ID] [varchar](8000)  NULL,
	[COLLISION_ID] [varchar](8000)  NULL,
	[CRASH_DATE] [varchar](8000)  NULL,
	[CRASH_TIME] [varchar](8000)  NULL,
	[VEHICLE_ID] [varchar](8000)  NULL,
	[STATE_REGISTRATION] [varchar](8000)  NULL,
	[VEHICLE_TYPE] [varchar](8000)  NULL,
	[VEHICLE_MAKE] [varchar](8000)  NULL,
	[VEHICLE_MODEL] [varchar](8000)  NULL,
	[VEHICLE_YEAR] [varchar](8000)  NULL,
	[TRAVEL_DIRECTION] [varchar](8000)  NULL,
	[VEHICLE_OCCUPANTS] [varchar](8000)  NULL,
	[DRIVER_SEX] [varchar](8000)  NULL,
	[DRIVER_LICENSE_STATUS] [varchar](8000)  NULL,
	[DRIVER_LICENSE_JURISDICTION] [varchar](8000)  NULL,
	[PRE_CRASH] [varchar](8000)  NULL,
	[POINT_OF_IMPACT] [varchar](8000)  NULL,
	[VEHICLE_DAMAGE] [varchar](8000)  NULL,
	[VEHICLE_DAMAGE_1] [varchar](8000)  NULL,
	[VEHICLE_DAMAGE_2] [varchar](8000)  NULL,
	[VEHICLE_DAMAGE_3] [varchar](8000)  NULL,
	[PUBLIC_PROPERTY_DAMAGE] [varchar](8000)  NULL,
	[PUBLIC_PROPERTY_DAMAGE_TYPE] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_1] [varchar](8000)  NULL,
	[CONTRIBUTING_FACTOR_2] [varchar](8000)  NULL
)
GO ;